version: '3'  # Указываем версию Docker Compose.

services:  # Определяем сервисы.

  db:  # Сервис базы данных MySQL.
    image: mysql:8.1.0  # Используем официальный образ MySQL версии 5.7.
    volumes:  # Определяем примонтированные тома для базы данных.
      - ./db_data:/var/lib/mysql  # Том для хранения данных MySQL.
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Том для инициализации базы данных при первом запуске.
    environment:  # Задаем переменные окружения для настройки MySQL.
      MYSQL_ROOT_PASSWORD: password  # Пароль для суперпользователя (root).
      MYSQL_DATABASE: text  # Имя базы данных.
      MYSQL_USER: User  # Имя пользователя.
      MYSQL_PASSWORD: 123456789  # Пароль пользователя.
      MYSQL_COLLATION: latin1_swedish_ci

  web:  # Сервис веб-сервера Apache.
    build: .  # Собираем образ веб-сервера из текущей директории, используя Dockerfile.
    ports:  # Прокидываем порты для доступа к веб-серверу.
      - "8081:80"  # Порт 8080 хоста прокидывается на порт 80 контейнера.
    volumes:  # Определяем примонтированный том для кода веб-приложения.
      - ./html:/var/www/html  # Том для хранения файлов веб-приложения.
    links:  # Создаем связь с сервисом базы данных.
      - db  # Веб-сервер будет в одной сети с контейнером базы данных.

volumes:  # Определяем именованный том для данных базы данных.
  db_data:

